[package]
name = "wasmtime_bindings"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0.83", features = ["c++20"] }
wasmtime-wasi = "8.0.1"
futures = "0.3.25"
anyhow = "1.0.66"

[dependencies.wasmtime]
version = "8.0.1"
default-features = false
features = ["async", "wat", "cranelift"]
