[tool.poetry]
name = "scylla"
description = "Scylla Documentation"
version = "4.3.0"
authors = ["ScyllaDB Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "6.0.1"
pygments = "2.15.1"
recommonmark = "0.7.1"
sphinx-scylladb-theme = "~1.5.1"
sphinx-sitemap = "2.5.0"
sphinx-autobuild = "2021.3.14"
Sphinx = "4.3.2"
sphinx-multiversion-scylla = "~0.2.10"
sphinx-markdown-tables = "0.0.15"
redirects_cli ="~0.1.2"
sphinxcontrib-datatemplates = "^0.9.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
