[tool.poetry]
name = "scylla"
description = "Scylla Documentation"
version = "4.3.0"
authors = ["ScyllaDB Contributors"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "5.3"
pygments = "2.2.0"
recommonmark = "0.5.0"
sphinx-scylladb-theme = "~0.1.11"
sphinx-sitemap = "2.1.0"
sphinx-autobuild = "0.7.1"
Sphinx = "2.4.4"
sphinx-multiversion-scylla = "0.2.4"
sphinx-markdown-tables = "0.0.15"

[tool.poetry.dev-dependencies]
pytest = "5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
